#!/bin/bash
FILES=(
"docker/docker-compose.yml"
"docker/init-scripts/01-create-extensions.sql"
"backend/WaySpot.Core/Enums/UserRole.cs"
"backend/WaySpot.Core/Entities/AppUser.cs"
"backend/WaySpot.Core/Entities/Business.cs"
"backend/WaySpot.Core/Entities/Post.cs"
"backend/WaySpot.Core/Entities/Review.cs"
"backend/WaySpot.Core/Entities/SavedRoute.cs"
"backend/WaySpot.Infrastructure/Data/WaySpotDbContext.cs"
"backend/WaySpot.Infrastructure/Data/Configurations/BusinessConfiguration.cs"
"backend/WaySpot.Infrastructure/Data/Configurations/ReviewConfiguration.cs"
"backend/WaySpot.API/appsettings.json"
"backend/WaySpot.API/Program.cs"
"backend/WaySpot.Core/DTOs/RegisterRequest.cs"
"backend/WaySpot.Core/DTOs/LoginRequest.cs"
"backend/WaySpot.Core/DTOs/AuthResponse.cs"
"backend/WaySpot.Core/Interfaces/IJwtService.cs"
"backend/WaySpot.Infrastructure/Services/JwtService.cs"
"backend/WaySpot.Core/Interfaces/IPasswordService.cs"
"backend/WaySpot.Infrastructure/Services/PasswordService.cs"
"backend/WaySpot.API/Controllers/AuthController.cs"
"backend/WaySpot.Core/DTOs/CreateBusinessRequest.cs"
"backend/WaySpot.Core/DTOs/BusinessResponse.cs"
"backend/WaySpot.API/Controllers/BusinessController.cs"
"backend/WaySpot.Core/DTOs/CreatePostRequest.cs"
"backend/WaySpot.Core/DTOs/PostResponse.cs"
"backend/WaySpot.API/Controllers/PostsController.cs"
"backend/WaySpot.Core/DTOs/DiscoverRequest.cs"
"backend/WaySpot.Core/DTOs/DiscoverResponse.cs"
"backend/WaySpot.API/Controllers/DiscoverController.cs"
"backend/WaySpot.Core/DTOs/CreateReviewRequest.cs"
"backend/WaySpot.Core/DTOs/ReviewResponse.cs"
"backend/WaySpot.API/Controllers/ReviewsController.cs"
"backend/WaySpot.API/Middleware/GlobalExceptionHandler.cs"
"backend/WaySpot.Core/Interfaces/IGeoJsonLdService.cs"
"backend/WaySpot.Infrastructure/Services/GeoJsonLdService.cs"
"backend/WaySpot.API/Controllers/GeoController.cs"
"cloudflare/worker.js"
"frontend/src/index.css"
"frontend/src/components/MapView.jsx"
"frontend/src/App.jsx"
"frontend/src/components/RoutePlanner.jsx"
"frontend/src/components/DiscoverMarkers.jsx"
"backend/WaySpot.Core/DTOs/RouteSearchRequest.cs"
"backend/WaySpot.Core/DTOs/RouteSearchResponse.cs"
"backend/WaySpot.API/Controllers/McpController.cs"
)

for file in "${FILES[@]}"; do
  if [ ! -f "$file" ]; then
    echo "MISSING: $file"
  else
    echo "EXISTS: $file"
  fi
done
